%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jacopobiancat/Documents/Scuola/2021-22/Astro_PI/MATLAB/GREENPI/Data/data_file.csv
%
% Auto-generated by MATLAB on 01-Jun-2022 12:40:41

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Line", "DataTime", "Temperature", "Humidity", "Pressure", "Sunlit", "Latitude", "Longitude", "Elevation", "Red", "Blue", "Green", "Clear", "CpuTemperature"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("/Users/jacopobiancat/Documents/Scuola/2021-22/Astro_PI/MATLAB/GREENPI/Data/data_file.csv", opts);


%% Clear temporary variables
clear opts