function data = Importfile4Columns(filename)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /MATLAB Drive/Data/Bambu_raw_data.csv
%
% Auto-generated by MATLAB on 20-Dec-2021 10:57:19

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Humidity", "Temperature", "Luminosity"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);


%% Clear temporary variables
clear opts